//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectHR.Domains
{
    using System;
    using System.Collections.Generic;
    
    public partial class Change
    {
        public int Id { get; set; }
        public System.DateTime ChangeDateTime { get; set; }
        public string PropertyName { get; set; }
        public string NewValue { get; set; }
        public string OldValue { get; set; }
    
        public virtual Employee SubjectEmployee { get; set; }
    }
}
